version: '3'

services:
  brapi.org:
    image: brapicoordinatorselby/brapi.org
    restart: unless-stopped
    volumes:
      - /home/selbyp/brapi.org/data/server-conf/certbot/conf:/etc/letsencrypt
      - /home/selbyp/brapi.org/data/server-conf/certbot/www:/var/www/certbot
      - /home/selbyp/brapi.org/brapi-website/site:/var/www/html
    ports:
      - "80:80"
      - "443:443"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - /home/selbyp/brapi.org/data/server-conf/certbot/conf:/etc/letsencrypt
      - /home/selbyp/brapi.org/data/server-conf/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
networks:
    default:
        external:
            name: brapi_net
